name: Monitor Page Screenshot

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install puppeteer nodemailer
      - run: node monitor/monitor.js
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}